version: '3.6'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_express
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data